-- FleetPulse Initial Schema
-- Devices registered with the fleet

CREATE TABLE devices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  hostname text NOT NULL,
  serial_number text UNIQUE NOT NULL,
  os_type text NOT NULL,
  os_version text,
  assigned_user text,
  department text,
  enrolled_at timestamptz DEFAULT now() NOT NULL,
  last_seen timestamptz,
  status text DEFAULT 'offline' NOT NULL
);

-- API tokens for device authentication (token stored as hash)

CREATE TABLE api_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  device_id uuid NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
  token_hash text NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  revoked bool DEFAULT false NOT NULL
);

CREATE INDEX idx_api_tokens_device_id ON api_tokens(device_id);
CREATE INDEX idx_api_tokens_token_hash ON api_tokens(token_hash) WHERE revoked = false;

-- Metrics from device heartbeats

CREATE TABLE metrics (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  device_id uuid NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
  timestamp timestamptz DEFAULT now() NOT NULL,
  cpu_pct float,
  ram_pct float,
  ram_total_gb float,
  disk_pct float,
  disk_total_gb float,
  battery_health_pct float,
  battery_cycles int,
  uptime_seconds bigint,
  filevault_enabled bool,
  bitlocker_enabled bool,
  firewall_enabled bool
);

CREATE INDEX idx_metrics_device_timestamp ON metrics(device_id, timestamp DESC);

-- Process snapshots from inventory

CREATE TABLE processes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  device_id uuid NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
  timestamp timestamptz DEFAULT now() NOT NULL,
  process_name text NOT NULL,
  cpu_pct float,
  ram_mb float
);

CREATE INDEX idx_processes_device_timestamp ON processes(device_id, timestamp DESC);

-- Software inventory per device

CREATE TABLE software_inventory (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  device_id uuid NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
  app_name text NOT NULL,
  version text,
  last_seen timestamptz DEFAULT now() NOT NULL,
  UNIQUE(device_id, app_name)
);

CREATE INDEX idx_software_inventory_device ON software_inventory(device_id);

-- Alerts generated by check-alerts cron

CREATE TABLE alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  device_id uuid NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
  alert_type text NOT NULL,
  severity text NOT NULL,
  message text NOT NULL,
  resolved bool DEFAULT false NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  resolved_at timestamptz
);

CREATE INDEX idx_alerts_device_resolved ON alerts(device_id, resolved);
CREATE INDEX idx_alerts_created ON alerts(created_at DESC);

-- Global config (alert thresholds, Slack webhook, etc.)

CREATE TABLE config (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text UNIQUE NOT NULL,
  value jsonb NOT NULL
);

-- Row Level Security

ALTER TABLE devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE processes ENABLE ROW LEVEL SECURITY;
ALTER TABLE software_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE config ENABLE ROW LEVEL SECURITY;

-- Policies: service role and anon can access for Edge Functions and dashboard.
-- Restrict config write to service role / admin checks in Edge Functions.

-- Dashboard (anon key) can read and update alerts/config; Edge Functions use service_role (bypasses RLS)
CREATE POLICY "Anon read devices" ON devices FOR SELECT TO anon USING (true);
CREATE POLICY "Anon read metrics" ON metrics FOR SELECT TO anon USING (true);
CREATE POLICY "Anon read processes" ON processes FOR SELECT TO anon USING (true);
CREATE POLICY "Anon read software_inventory" ON software_inventory FOR SELECT TO anon USING (true);
CREATE POLICY "Anon read alerts" ON alerts FOR SELECT TO anon USING (true);
CREATE POLICY "Anon update alerts" ON alerts FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Anon read config" ON config FOR SELECT TO anon USING (true);
CREATE POLICY "Anon update config" ON config FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Anon insert config" ON config FOR INSERT TO anon WITH CHECK (true);

-- Default config rows

INSERT INTO config (key, value) VALUES
  ('alert_thresholds', '{"disk_warning": 85, "disk_critical": 95, "ram_warning": 90, "battery_warning": 60, "offline_minutes": 120, "min_os_version_mac": "13.0", "min_os_version_windows": "10.0.19041"}'::jsonb),
  ('slack_webhook', '{"url": ""}'::jsonb),
  ('daily_digest_time', '{"hour": 9}'::jsonb);
